### ISSUE TITLE
403's don't cause the metrics exporter to re-establish a session

### ISSUE THREAD

**Issue by lexton** [spacelift-io/prometheus-exporter#10]
We updated our login policies on the account - and this invalidated the existing session.

The API Token was still valid - but we had to kill the running process in order for it to pick up the token again leading to a drop in metrics.

**Comment by adamconnelly** [comment]
@lexton apologies on the slow response here. This has been fixed in v0.2.1: https://github.com/spacelift-io/prometheus-exporter/releases/tag/v0.2.1.

Thanks a lot for reporting this!
